"""empty message

Revision ID: 297c1b7cfcf4
Revises: 1073f8b7d6dd
Create Date: 2022-05-16 14:05:28.735448

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '297c1b7cfcf4'
down_revision = '1073f8b7d6dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('digital_ids')
    op.add_column('checks', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('checks', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('validation_details', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('validation_details', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('validation_documents', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('validation_documents', sa.Column('update_date', sa.DateTime(), nullable=True))
    op.add_column('validations', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('validations', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('validations', 'updated_at')
    op.drop_column('validations', 'created_at')
    op.drop_column('validation_documents', 'update_date')
    op.drop_column('validation_documents', 'created_at')
    op.drop_column('validation_details', 'updated_at')
    op.drop_column('validation_details', 'created_at')
    op.drop_column('checks', 'updated_at')
    op.drop_column('checks', 'created_at')
    op.create_table('digital_ids',
    sa.Column('id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('creation_date', mysql.DATETIME(), nullable=True),
    sa.Column('update_date', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###
