"""empty message

Revision ID: 2e29b7c986eb
Revises: 
Create Date: 2021-08-27 18:17:13.669701

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils import UUIDType


# revision identifiers, used by Alembic.
revision = '2e29b7c986eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actividad_economica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave_economica', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('results_ine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', UUIDType(binary=False), nullable=True),
    sa.Column('sub_nombre_economica', sa.String(length=255), nullable=True),
    sa.Column('sub_clave_economica_id', sa.String(length=20), nullable=True),
    sa.Column('email_user', sa.String(length=255), nullable=True),
    sa.Column('mensaje_error', sa.String(length=255), nullable=True),
    sa.Column('rid_solicitud', sa.BigInteger(), nullable=True),
    sa.Column('status_ine_loads', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('cat_actividad_economica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cat_nombre_economica', sa.String(length=100), nullable=True),
    sa.Column('cat_actividad_economica_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cat_actividad_economica_id'], ['actividad_economica.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sub_cat_actividad_economica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sub_nombre_economica', sa.String(length=255), nullable=True),
    sa.Column('sub_clave_economica_id', sa.String(length=20), nullable=True),
    sa.Column('sub_cat_actividad_economica_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sub_cat_actividad_economica_id'], ['cat_actividad_economica.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sub_cat_actividad_economica')
    op.drop_table('cat_actividad_economica')
    op.drop_table('results_ine')
    op.drop_table('actividad_economica')
    # ### end Alembic commands ###
