"""empty message

Revision ID: 6ca1a352566e
Revises: 9cd9dd490559
Create Date: 2022-05-11 20:24:50.786575

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '6ca1a352566e'
down_revision = '9cd9dd490559'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checks',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('cic', sa.String(length=255), nullable=True),
    sa.Column('citizen_id', sa.String(length=255), nullable=True),
    sa.Column('company_summary', sqlalchemy_utils.types.json.JSONType(), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('document_recognition_id', sa.String(length=255), nullable=True),
    sa.Column('elector_key', sa.String(length=255), nullable=True),
    sa.Column('expedition_date', sa.DateTime(), nullable=True),
    sa.Column('issue_date', sa.DateTime(), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('name_score', sa.Integer(), nullable=True),
    sa.Column('id_score', sa.Integer(), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('ocr', sa.String(length=255), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('scores', sqlalchemy_utils.types.json.JSONType(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('statuses', sqlalchemy_utils.types.json.JSONType(), nullable=True),
    sa.Column('summary', sqlalchemy_utils.types.json.JSONType(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('vehicle_summary', sqlalchemy_utils.types.json.JSONType(), nullable=True),
    sa.Column('national_id', sa.String(length=255), nullable=True),
    sa.Column('owner_document_type', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('process_ids', sa.Column('first_check_id', sa.String(length=255), nullable=True))
    op.add_column('process_ids', sa.Column('last_check_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_process_ids_first_check_id'), 'process_ids', ['first_check_id'], unique=False)
    op.create_index(op.f('ix_process_ids_last_check_id'), 'process_ids', ['last_check_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_process_ids_last_check_id'), table_name='process_ids')
    op.drop_index(op.f('ix_process_ids_first_check_id'), table_name='process_ids')
    op.drop_column('process_ids', 'last_check_id')
    op.drop_column('process_ids', 'first_check_id')
    op.drop_table('checks')
    # ### end Alembic commands ###
