"""empty message

Revision ID: 9d71a180a2e9
Revises: 2e29b7c986eb
Create Date: 2021-09-10 13:08:10.238613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d71a180a2e9'
down_revision = '2e29b7c986eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results_ine', sa.Column('front', sa.String(length=255), nullable=True))
    op.add_column('results_ine', sa.Column('back', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results_ine', 'back')
    op.drop_column('results_ine', 'front')
    # ### end Alembic commands ###
